<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>profileEmail</name>
   <tag></tag>
   <elementGuidId>7e0764fe-ebbb-407f-8177-60d1c762c6ce</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.widget.TextView</value>
      <webElementGuid>0bf6443e-0de3-4a49-a449-28d38c1fb818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>rianfati@gmail.com</value>
      <webElementGuid>3a152cba-f690-47fc-a1b3-174849ec7147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>resource-id</name>
      <type>Main</type>
      <value>com.she.sehatq:id/tvEmail</value>
      <webElementGuid>08c17251-4611-4406-8a53-e53e8671c2ce</webElementGuid>
   </webElementProperties>
   <locator>//*[@resource-id = 'com.she.sehatq:id/tvEmail']</locator>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
</MobileElementEntity>
